# Generated by Django 5.2.1 on 2025-05-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='dt_modified', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='dt_modified', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='dt_modified', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_column='dt_modified', null=True),
        ),
    ]
